// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_two.DbContexts;

namespace Project_two.Migrations
{
    [DbContext(typeof(AirlineContext))]
    [Migration("20220608163852_update_Airline_Logo")]
    partial class update_Airline_Logo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_two.Model.Admin", b =>
                {
                    b.Property<int>("adminId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("adminEmailId");

                    b.Property<string>("adminName");

                    b.Property<string>("adminPasskey");

                    b.HasKey("adminId");

                    b.ToTable("Admin");

                    b.HasData(
                        new { adminId = 1, adminEmailId = "Admin1", adminName = "Admin1", adminPasskey = "Admin1" },
                        new { adminId = 2, adminEmailId = "Admin2", adminName = "Admin2", adminPasskey = "Admin2" }
                    );
                });

            modelBuilder.Entity("Project_two.Model.Airline", b =>
                {
                    b.Property<int>("airlineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("airlineAddress");

                    b.Property<int>("airlineContactNumber");

                    b.Property<string>("airlineLogo");

                    b.Property<string>("airlineName");

                    b.HasKey("airlineId");

                    b.ToTable("Airlines");
                });
#pragma warning restore 612, 618
        }
    }
}
