// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_two.DbContexts;

namespace Project_two.Migrations
{
    [DbContext(typeof(AirlineContext))]
    [Migration("20220608054350_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_two.Model.Airline", b =>
                {
                    b.Property<int>("airlineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("airlineAddress");

                    b.Property<int>("airlineContactNumber");

                    b.Property<string>("airlineLogo");

                    b.Property<string>("airlineName");

                    b.HasKey("airlineId");

                    b.ToTable("Airlines");
                });
#pragma warning restore 612, 618
        }
    }
}
